apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - cronjob.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: eks-image-updater
    envs: [eks-image-updater.env]
    namespace: cicd
namespace: cicd
