name: Go Test

on: [push]

jobs:
  test:
    env:
      IS_TEST: true
    strategy:
      fail-fast: false
      matrix:
        go: [1.17.x, 1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install Dependencies
        run: go mod download
      - name: Go Test
        run: go test -race $(go list ./...)
